version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "./functions/package.json" }}
      - run:
          name: install-npm-dependencies
          command: npm --prefix ./functions install ./functions
      - save_cache:
          key: dependency-cache-{{ checksum "./functions/package.json" }}
          paths:
            - ./functions/node_modules
      - run:
          name: deploy
          command: npx firebase deploy --token=$FIREBASE_TOKEN --non-interactive